global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Убедись, что это правильный адрес Spring Boot приложения
